apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payments

spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app:  payments
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  payments
        image:  nginx:alpine
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
        