apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app:  payments
    spec:
      containers:
      - name:  payments
        image: goapp:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
        